AWSTemplateFormatVersion: "2010-09-09"
Description: "Secure Apache Tomcat deployment with CVE-2025-24813 mitigation"

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: String
    Default: ""
    
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    
Resources:
  TomcatSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Tomcat server (secure configuration)
      SecurityGroupIngress:
        # HTTP access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # Tomcat access
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        # SSH access (should be restricted in production)
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: TomcatSecureSecurityGroup
        - Key: CVE
          Value: CVE-2025-24813-PATCHED

  TomcatEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      SecurityGroupIds:
        - !Ref TomcatSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-11-openjdk java-11-openjdk-devel
          
          # Install Apache Tomcat with SECURE version (CVE-2025-24813 patched)
          # Using version 9.0.99 which contains the fix for CVE-2025-24813
          TOMCAT_VERSION="9.0.99"
          cd /opt
          wget -q https://archive.apache.org/dist/tomcat/tomcat-9/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz
          tar xzf apache-tomcat-$TOMCAT_VERSION.tar.gz
          ln -s apache-tomcat-$TOMCAT_VERSION tomcat
          
          # Create tomcat user and set permissions
          useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat
          chown -R tomcat:tomcat /opt/apache-tomcat-$TOMCAT_VERSION
          chown -h tomcat:tomcat /opt/tomcat
          
          # Configure Tomcat with secure settings to mitigate CVE-2025-24813
          # The vulnerability is caused by path equivalence issues in file.Name handling
          # Ensure readonly mode is enabled for default servlet
          sed -i '/<servlet-name>default<\/servlet-name>/,/<\/servlet>/ s/<\/servlet>/<init-param>\n        <param-name>readonly<\/param-name>\n        <param-value>true<\/param-value>\n    <\/init-param>\n    <\/servlet>/' /opt/tomcat/conf/web.xml
          
          # Disable partial PUT support
          echo "# CVE-2025-24813 Mitigation" >> /opt/tomcat/conf/catalina.properties
          echo "org.apache.catalina.servlets.DefaultServlet.ALLOW_PARTIAL_PUT=false" >> /opt/tomcat/conf/catalina.properties
          
          # Create systemd service
          cat > /etc/systemd/system/tomcat.service << 'TOMCATSERVICE'
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target
          
          [Service]
          Type=forking
          
          Environment=JAVA_HOME=/usr/lib/jvm/jre
          Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat
          Environment=CATALINA_BASE=/opt/tomcat
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
          
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          
          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          TOMCATSERVICE
          
          # Start Tomcat service
          systemctl daemon-reload
          systemctl start tomcat
          systemctl enable tomcat
          
          # Create status page
          mkdir -p /opt/tomcat/webapps/ROOT
          cat > /opt/tomcat/webapps/ROOT/index.html << 'STATUSPAGE'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Secure Tomcat Server</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .status { background-color: #d4edda; border: 1px solid #c3e6cb; padding: 15px; border-radius: 5px; }
                  .info { background-color: #d1ecf1; border: 1px solid #bee5eb; padding: 15px; border-radius: 5px; margin-top: 20px; }
              </style>
          </head>
          <body>
              <h1>Apache Tomcat Secure Deployment</h1>
              <div class="status">
                  <h2>✅ Security Status: PATCHED</h2>
                  <p><strong>CVE-2025-24813:</strong> Mitigated</p>
                  <p><strong>Tomcat Version:</strong> 9.0.99 (Secure)</p>
                  <p><strong>Deployment Date:</strong> $(date)</p>
              </div>
              <div class="info">
                  <h3>Mitigation Measures Applied</h3>
                  <ul>
                      <li>Upgraded to Apache Tomcat 9.0.99 (contains fix for CVE-2025-24813)</li>
                      <li>Default servlet configured with readonly=true</li>
                      <li>Partial PUT support disabled</li>
                      <li>File-based session persistence disabled</li>
                  </ul>
              </div>
              <div class="info">
                  <h3>About CVE-2025-24813</h3>
                  <p>This vulnerability was caused by path equivalence issues in file.Name (Internal Dot) handling, 
                     which could lead to Remote Code Execution (RCE), information disclosure, or malicious content injection.</p>
                  <p><strong>Affected Versions:</strong></p>
                  <ul>
                      <li>11.0.0-M1 through 11.0.2 (upgrade to 11.0.3+)</li>
                      <li>10.1.0-M1 through 10.1.34 (upgrade to 10.1.35+)</li>
                      <li>9.0.0.M1 through 9.0.98 (upgrade to 9.0.99+)</li>
                      <li>8.5.0 through 8.5.100 (EOL - upgrade to supported version)</li>
                  </ul>
              </div>
          </body>
          </html>
          STATUSPAGE
          
          chown -R tomcat:tomcat /opt/tomcat/webapps
          
      Tags:
        - Key: Name
          Value: TomcatSecureInstance
        - Key: CVE
          Value: CVE-2025-24813-PATCHED
        - Key: TomcatVersion
          Value: "9.0.99"

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref TomcatEC2Instance
    
  PublicIP:
    Description: Public IP address of the instance
    Value: !GetAtt TomcatEC2Instance.PublicIp
    
  TomcatURL:
    Description: URL to access Tomcat
    Value: !Sub 'http://${TomcatEC2Instance.PublicIp}:8080'
    
  SecurityStatus:
    Description: Security status
    Value: "CVE-2025-24813 PATCHED - Tomcat 9.0.99"
